/*Tablas*/
/*Mi base de datos va a ser de diferentes tiendas*/

/*En la tabla dueños, guardamos dni, nombre, apellidos y ciudad de nacimiento del dueño*/

CREATE TABLE DUENIOS(
    DNI CHAR(9) CONSTRAINT DUE_DNI_PK PRIMARY KEY,
    NOMBRE VARCHAR2(20) CONSTRAINT DUE_NOM_NN NOT NULL,
    APELLIDOS VARCHAR2(20) CONSTRAINT DUE_APE_NN NOT NULL,
    CIUDAD VARCHAR2(20)  CONSTRAINT DUE_CIU_NN NOT NULL
);

/*En la tabla tienda guardaremos nombre, dueño, que será foranea a la tabla dueños, ciudad donde está la tienda y fecha de apertura*/
CREATE TABLE TIENDA(
    NOMBRE VARCHAR2(30) CONSTRAINT TIE_NOM_PK PRIMARY KEY,
    DUENIO CHAR(9) CONSTRAINT DUE_TIE_FK REFERENCES DUENIOS,
    CIUDAD VARCHAR2(20) CONSTRAINT TIE_CIU_NN NOT NULL,
    FECHA_APERTURA DATE CONSTRAINT TIE_FEC_NN NOT NULL
);

/*
    en la tabla departamentos guardamos un codigo de departamentos, nombre de la tienda que apunta a tienda, desempeño
    y nombre departamento
*/

CREATE TABLE DEPARTAMENTOS (
    
    COD_DEPARTAMENTO CHAR(8) CONSTRAINT DEP_COD_PK PRIMARY KEY,
    NOMBRE_TIENDA VARCHAR2(30) CONSTRAINT DEP_TIE_FK REFERENCES TIENDA,
    DESEMPENIO VARCHAR2(30) CONSTRAINT DEP_DES_NN NOT NULL,
    NOMBRE_DEP VARCHAR2(30) CONSTRAINT DEP_NOM_NN NOT NULL
    
);

/*En la tabla empleado guardaremos id de empleado, nombre, fecha nacimiento, tienda donde trabaja que apunta a tienda y cargo que tiene que
ser entre los que está en la lista*/

CREATE TABLE EMPLEADO(
    ID_EMPLEADO CHAR(8) CONSTRAINT EMP_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(30) CONSTRAINT EMP_NOM_NN NOT NULL,
    FECHANAC DATE CONSTRAINT EMP_FEC_NN NOT NULL,
    TIENDA VARCHAR2(30) CONSTRAINT TIE_EMP_FK REFERENCES TIENDA,
    CARGO VARCHAR2(10) CONSTRAINT EMP_CAR_NN NOT NULL,
    DEPARTAMENTO CHAR(8) CONSTRAINT EMP_EMP_FK REFERENCES DEPARTAMENTOS,
    CONSTRAINT EMP_CAR_INR CHECK(CARGO IN ('CARGO1','CARGO2','CARGO3'))
    
);


--TABLAS DE AUDITORIA

CREATE TABLE AUDIT_DUENIO (    
    USUARIO	VARCHAR2(40),
    FECHA_HORA	TIMESTAMP,
    OPCION	NUMBER(1),
    OLD_REG	VARCHAR2(200),
    NEW_REG	VARCHAR2(200)
);
CREATE TABLE AUDIT_TIENDA (    
    USUARIO	VARCHAR2(40),
    FECHA_HORA	TIMESTAMP,
    OPCION	NUMBER(1),
    OLD_REG	VARCHAR2(200),
    NEW_REG	VARCHAR2(200)
);
CREATE TABLE AUDIT_DEPARTAMENTOS (    
    USUARIO	VARCHAR2(40),
    FECHA_HORA	TIMESTAMP,
    OPCION	NUMBER(1),
    OLD_REG	VARCHAR2(200),
    NEW_REG	VARCHAR2(200)
);

CREATE TABLE AUDIT_EMPLEADO (    
    USUARIO	VARCHAR2(40),
    FECHA_HORA	TIMESTAMP,
    OPCION	NUMBER(1),
    OLD_REG	VARCHAR2(200),
    NEW_REG	VARCHAR2(200)
);

/*
DROP TABLE EMPLEADO;
DROP TABLE DEPARTAMENTOS;
DROP TABLE TIENDA;
DROP TABLE DUENIOS;
DROP TABLE AUDIT_EMPLEADO;
DROP TABLE AUDIT_DEPARTAMENTOS;
DROP TABLE AUDIT_TIENDA;
DROP TABLE AUDIT_DUENIO;
*/
